version: '2'

services:
  mypython:
    image: pytest
    container_name: mypython
    volumes:
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
      - /mySocket.py:/mySocket.py
    user: "root"
    network_mode: host
    command: python ./mySocket.py
    restart: always